employee/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url


app_name = 'employee'

urlpatterns = [
    path('index', views.index, name="index"),
    path('', views.index, name="index"),
    path('vehicles', views.vehicles, name="vehicles"),
    path('new_vehicle', views.new_vehicle, name="new_vehicle"),
    path('add_vehicle', views.add_vehicle, name="add_vehicle"),
    path('vehicle_details/<slug:vehicle_id>', views.vehicle_details, name="vehicle_details"),
    path('edit_vehicle/<slug:vehicle_id>', views.edit_vehicle, name="edit_vehicle"),

    path('bookings', views.bookings, name="bookings"), 
    path('employees', views.employees, name="employees"),
    path('new_employee', views.new_employee, name="new_employee"),
    path('employee_detail', views.employee_detail, name="employee_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_view



urlpatterns = [
    path('admin/', admin.site.urls),
       
    path('', include('employee.urls')),    
    
    path('accounts/', include('django.contrib.auth.urls')),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employee/models.py
from django.db import models
import uuid


from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


from django.utils import timezone
import datetime

 

class CustomUser(AbstractUser):
    is_admin = models.BooleanField(default=False,blank=True)
    is_super_admin = models.BooleanField(default=False,blank=True)

    def __str__(self):
        return self.username
  

class Employee(models.Model):
    employee_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50,blank=True)
    contact = models.CharField(max_length=50,blank=True)
    email = models.EmailField(max_length=254)
    address = models.CharField(max_length=50,blank=True)
    status = models.CharField(max_length=50,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Admin(models.Model):
    admin_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50,blank=True)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    contact = models.CharField(max_length=50,blank=True)
    email = models.EmailField(max_length=254)
    address = models.CharField(max_length=50,blank=True)
    status = models.CharField(max_length=50,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TimeSlot(models.Model):
    employee_shift_time = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    employee_name = models.ForeignKey('Employee', on_delete=models.CASCADE)

class Vehicle(models.Model):
    vehicle_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    license_plate = models.CharField(max_length=50,blank=True)
    vehicle_contact = models.CharField(max_length=50,blank=True)
    vehicle_color = models.CharField(max_length=50,blank=True)
    driver_name = models.CharField(max_length=50,blank=True)
    vehicle_description = models.CharField(max_length=500,blank=True)


    status = models.CharField(max_length=50,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.license_plate

class VehicleAvailability(models.Model):
    vehicle_plate = models.ForeignKey('Vehicle', on_delete=models.CASCADE)
    time_slot = models.ForeignKey('TimeSlot', on_delete=models.CASCADE)
    status = models.CharField(max_length=50,blank=True)

class Booking(models.Model):
    booking_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    employee_name = models.ForeignKey('Employee', on_delete=models.CASCADE)
    vehicle_plate = models.ForeignKey('Vehicle', on_delete=models.CASCADE)
    
    start_time = models.CharField(max_length=50,blank=True)
    end_time = models.CharField(max_length=50,blank=True)
    pickup_address = models.CharField(max_length=50,blank=True)
    dropoff_address = models.CharField(max_length=50,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.employee_name



class Report(models.Model):
    report_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    report_title = models.CharField(max_length=50,blank=True)
    report_details = models.CharField(max_length=500,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.report_title

employee/views.py
from django.shortcuts import render

from django.shortcuts import render,reverse,redirect,get_object_or_404
from django.http import HttpResponseRedirect

from . models import *


from django.conf import settings
from django.dispatch import receiver
from django.http import HttpRequest
from django.middleware.csrf import get_token

from django.contrib.auth.decorators import login_required

from django.contrib import messages, auth

from django.db import IntegrityError
from django.http import JsonResponse
# from django.shortcuts import render_to_response



@login_required
def index(request):
    context = {
        "a":"mm-active"
    }
    return render(request,"employee/admin/dashboard.html",context)

def bookings(request):
    vehicles = Vehicle.objects.all()
    context = {
        "fa":"mm-active",
        "vehicles": vehicles
    }

    return render(request,"employee/admin/bookings.html",context)

def vehicles(request):
    vehicles = Vehicle.objects.all()
    context = {
        "ba":"mm-active",
        "vehicles": vehicles
    }

    return render(request,"employee/admin/vehicles.html",context)


def new_vehicle(request):
    context = {
        "bb":"mm-active"
    }
    return render(request,"employee/admin/new-vehicle.html",context)


def add_vehicle(request):
    if request.method == 'POST':
      
        new_vehicle = Vehicle(
            license_plate=request.POST['license_plate'],
            vehicle_contact=request.POST['vehicle_contact'],
            vehicle_color=request.POST['vehicle_color'])

        new_vehicle.save()
                
        messages.success(request, "a")
        request.session['foo'] = 2
        return HttpResponseRedirect(reverse('employee:vehicles'))





 


def vehicle_details(request,vehicle_id):
    vehicle = Vehicle.objects.get(vehicle_id=vehicle_id)
    context = {
    
         "ba":"mm-active",
        'vehicle': vehicle
    }
    return render(request,"employee/admin/vehicle-details.html",context)


def edit_vehicle(request,vehicle_id):
    vehicle = Vehicle.objects.get(vehicle_id=vehicle_id)
    vehicle.license_plate=request.POST['license_plate']
    vehicle.vehicle_contact=request.POST['vehicle_contact']
    vehicle.vehicle_color=request.POST['vehicle_color']
    vehicle.driver_name=request.POST['driver_name']
    vehicle.vehicle_description=request.POST['vehicle_description']
    
    vehicle.save()
    return HttpResponseRedirect(reverse('employee:vehicle_details', kwargs={'vehicle_id':vehicle_id}))
    # return render(request,"employee/admin/vehicle-details.html",context)

def employees(request):
    context = {
        "ca":"mm-active"
    }
    return render(request,"employee/admin/employees.html",context)


def new_employee(request):
    context = {
        "cb":"mm-active"
    }
    return render(request,"employee/admin/new-employee.html",context)


def employee_detail(request):
    context = {
        "c":"mm-active"
    }
    return render(request,"employee/admin/employee-detail.html",context)

employee/templates/employee/admin/base.html
<!doctype html>
<html lang="en">
    
<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Responsive Bootstrap 4 Admin &amp; Dashboard Template">
        <meta name="author" content="Bdtask">
        <title>UBC Travel</title>
        <!-- App favicon -->
        <link rel="shortcut icon" href="/static/employee/assets/plugins/img/ubc.png">
        <!--Global Styles(used by all pages)-->
        <link href="/static/employee/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/employee/assets/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
        <link href="/static/employee/assets/plugins/fontawesome/css/all.min.css" rel="stylesheet">
        <link href="/static/employee/assets/plugins/typicons/src/typicons.min.css" rel="stylesheet">
        <link href="/static/employee/assets/plugins/themify-icons/themify-icons.min.css" rel="stylesheet">
         <link href="static/employee/assets/plugins/NotificationStyles/css/ns-default.css" rel="stylesheet">
        <link href="static/employee/assets/plugins/NotificationStyles/css/ns-style-growl.css" rel="stylesheet">
        <link href="static/employee/assets/plugins/NotificationStyles/css/ns-style-attached.css" rel="stylesheet">
        <link href="static/employee/assets/plugins/NotificationStyles/css/ns-style-bar.css" rel="stylesheet">
        <link href="static/employee/assets/plugins/NotificationStyles/css/ns-style-other.css" rel="stylesheet">
        <!--Third party Styles(used by this page)--> 
        <link href="/static/employee/assets/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
        <!--Start Your Custom Style Now-->
        <link href="/static/employee/assets/plugins/css/style.css"  rel="stylesheet">

     
        </style>
    </head>
    <body class="fixed">
        <!-- Page Loader -->
        <div class="page-loader-wrapper">
            <div class="loader">
                <div class="preloader">
                    <div class="spinner-layer pl-green">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div>
                        <div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
                <p>Please wait...</p>
            </div>
        </div>
        <!-- #END# Page Loader -->
        <div class="wrapper">
            <!-- Sidebar  -->
            <nav class="sidebar sidebar-bunker">
                <div class="sidebar-header">
                    <!--<a href="index.html" class="logo"><span>bd</span>task</a>-->
                    <a href="index-2.html" class="logo"><img src="/static/employee/assets/plugins/img/ubc.png" alt=""></a>
                </div><!--/.sidebar header-->
                <div class="profile-element d-flex align-items-center flex-shrink-0">
                  
                    <div class="profile-text">
                        <h6 class="m-0">Super Admin</h6>
                    </div>
                </div><!--/.profile element-->
              
                <div class="sidebar-body">
                    <nav class="sidebar-nav">
                        <ul class="metismenu">
                      
                            <li class="{{a}}">
                                <a class="material-ripple" href={% url 'employee:index' %}>
                                    <i class="typcn typcn-home-outline mr-2"></i>
                                    Dashboard
                                </a>
                             
                            </li>
                           
                            <li>
                                <a class="has-arrow material-ripple" href="#">
                                    <i class="typcn typcn-group-outline  mr-2"></i>
                                    Employees
                                </a>
                                <ul class="nav-second-level">
                                <li class="{{cb}}"><a href={% url 'employee:new_employee' %}> Requests</a></li>
                                    <li class="{{ca}}"><a href={% url 'employee:employees' %}>Manage </a></li>
                                    
                                   
                                </ul>
                            </li>


                                 <li >
                                <a class="has-arrow material-ripple" href="#">
                                    <i class="typcn typcn-directions mr-2"></i>
                                    Transport Vehicles
                                </a>
                                <ul class="nav-second-level">
                                    <li class="{{ba}}"><a href={% url 'employee:vehicles' %}>Manage </a></li>
                                    <li class="{{bb}}"><a href={% url 'employee:new_vehicle' %}>Add New </a></li>
                                   
                                </ul>
                            </li>


                              <li>
                                <a class="material-ripple" href="#">
                                    <i class="typcn typcn-pin-outline  mr-2"></i>
                                    Addresses
                                </a>
                               
                            </li>


                              <li>
                                <a class="material-ripple" href="#">
                                    <i class="typcn typcn-stopwatch  mr-2"></i>
                                    Time & Shifts
                                </a>
                              
                            </li>

                                <li class="{{fa}}"> 
                                <a class="material-ripple" href={% url 'employee:bookings' %}>
                                    <i class="typcn typcn-chart-pie-outline mr-2"></i>
                                    Bookings
                                </a>
                             
                            </li>


                              <li>
                                <a class="material-ripple" href="#">
                                    <i class="typcn typcn-chart-bar-outline mr-2"></i>
                                    Reports & Stats
                                </a>
                             
                            </li>
                           
                        </ul>
                    </nav>
                </div><!-- sidebar-body -->
            </nav>
            <!-- Page Content  -->
            <div class="content-wrapper">
                <div class="main-content">
                    <nav class="navbar-custom-menu navbar navbar-expand-lg m-0">
                        <div class="sidebar-toggle-icon" id="sidebarCollapse">
                            sidebar toggle<span></span>
                        </div><!--/.sidebar toggle icon-->
                        <div class="d-flex flex-grow-1">
                            <ul class="navbar-nav flex-row align-items-center ml-auto">
                               
                                <li class="nav-item dropdown notification">
                                    <a class="nav-link dropdown-toggle badge-dot" href="#" data-toggle="dropdown">
                                        <i class="typcn typcn-bell"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <h6 class="notification-title">Notifications</h6>
                                        <p class="notification-text">You have no notifications</p>
                                       
                                        {% comment %} <div class="dropdown-footer"><a href="#">View All Notifications</a></div> {% endcomment %}
                                    </div><!--/.dropdown-menu -->
                                </li><!--/.dropdown-->
                                <li class="nav-item dropdown user-menu">
                                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                                        <!--<img src="/static/employee/assets/plugins/img/user2-160x160.png" alt="">-->
                                        <i class="typcn typcn-user-add-outline"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" >
                                        <div class="dropdown-header d-sm-none">
                                            <a href="#" class="header-arrow"><i class="icon ion-md-arrow-back"></i></a>
                                        </div>
                                        <div class="user-header">
                                            <div class="img-user">
                                                <img src="/static/employee/assets/plugins/img/admin.jpg" alt="">
                                            </div><!-- img-user -->
                                            <h6>Super Admin</h6>
                                        </div><!-- user-header -->
                                      
                                        <a href="#" class="dropdown-item"><i class="typcn typcn-key-outline"></i> Sign Out</a>
                                    </div><!--/.dropdown-menu -->
                                </li>
                            </ul><!--/.navbar nav-->
                            <div class="nav-clock">
                                <div class="time">
                                    <span class="time-hours"></span>
                                    <span class="time-min"></span>
                                    <span class="time-sec"></span>
                                </div>
                            </div><!-- nav-clock -->
                        </div>
                    </nav><!--/.navbar-->
              {% block content %}
              {% endblock content %}
                </div><!--/.main content-->
                <footer class="footer-content">
                    <div class="footer-text d-flex align-items-center justify-content-between">
                        <div class="copy">© 2020</div>
                       
                    </div>
                </footer><!--/.footer content-->
                <div class="overlay"></div>
            </div><!--/.wrapper-->
        </div>
        <!--Global script(used by all pages)-->
   
        <script src="/static/employee/assets/plugins/jQuery/jquery-3.4.1.min.js"></script>
        <script src="/static/employee/assets/plugins/js/popper.min.js"></script>
        <script src="/static/employee/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/employee/assets/plugins/metisMenu/metisMenu.min.js"></script>
        <script src="/static/employee/assets/plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
        <!-- Third Party Scripts(used by this page)-->
        <script src="/static/employee/assets/plugins/chartJs/Chart.min.js"></script>
        <script src="/static/employee/assets/plugins/sparkline/sparkline.min.js"></script>
        <script src="/static/employee/assets/plugins/datatables/dataTables.min.js"></script>
        <script src="/static/employee/assets/plugins/datatables/dataTables.bootstrap4.min.js"></script>
        <!--Page Active Scripts(used by this page)-->
        <script src="/static/employee/assets/plugins/js/pages/dashboard.js"></script>
        <!--Page Scripts(used by all page)-->
        <script src="/static/employee/assets/plugins/js/sidebar.js"></script>

           <script src=" https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

              <script src="static/employee/assets/plugins/NotificationStyles/js/notificationFx.js"></script>

                


             



          {% block scripts %}


        {% endblock scripts %}


    </body>

</html>

employee/templates/employee/admin/dashboard.html
{% extends 'employee/admin/base.html' %}
{% block content %}

 <!--Content Header (Page header)-->
                    <div class="content-header row align-items-center m-0">
                        <nav aria-label="breadcrumb" class="col-sm-4 order-sm-last mb-3 mb-sm-0 p-0 ">
                            <ol class="breadcrumb d-inline-flex font-weight-600 fs-13 bg-white mb-0 float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Dashboard</li>
                            </ol>
                        </nav>
                        <div class="col-sm-8 header-title p-0">
                            <div class="media">
                                <div class="header-icon text-success mr-3"><i class="typcn typcn-spiral"></i></div>
                                <div class="media-body">
                                    <h1 class="font-weight-bold">Dashboard</h1>
                                    <small>From now on you will start your activities.</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.Content Header (Page header)--> 
                   



{% endblock content %}



 

employee/templates/employee/admin/employee-requests.html
{% extends 'employee/admin/base.html' %}
{% block content %}

  <!--Content Header (Page header)-->
                    <div class="content-header row align-items-center m-0">
                        <nav aria-label="breadcrumb" class="col-sm-4 order-sm-last mb-3 mb-sm-0 p-0 ">
                            <ol class="breadcrumb d-inline-flex font-weight-600 fs-13 bg-white mb-0 float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Employees</a></li>
                                <li class="breadcrumb-item active">Manage</li>
                            </ol>
                        </nav>
                        <div class="col-sm-8 header-title p-0">
                            <div class="media">
                                <div class="header-icon text-success mr-3"><i class="typcn typcn-puzzle-outline"></i></div>
                                <div class="media-body">
                                    <h1 class="font-weight-bold">Employee Requests</h1>
                                    <small>These are the pips that ....</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.Content Header (Page header)--> 
                    <div class="body-content">
                        <!--HTML (DOM) sourced data-->
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">Sourced data</h6>
                                    </div>
                                   
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table display table-bordered table-striped table-hover sourced">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Contact</th>
                                                <th>Email</th>
                                                <th>Address</th>
                                                <th>Status</th>
                                                <th>Created</th>


                                                
                                            </tr>
                                        </thead>
                                        <tbody>



                                    {% for managers in m %}
                                     <tr>
                                                <td>{{m.name}}</td>
                                                <td>{{m.contact}}</td>
                                                <td>{{m.email}}</td>
                                                <td>{{m.address}}</td>
                                                <td>{{m.status}}</td>
                                                <td>{{m.created_at}}</td>
                                        </tr> 
                                            
                                    
                                    {% endfor %}

                          
                                        
                                        </tbody>
                                       
                                    </table>
                                </div>
                            </div>
                        </div>
                       
                    </div><!--/.body content-->

{% endblock content %}

employee/templates/employee/admin/new-vehicle.html
{% extends 'employee/admin/base.html' %}
{% block content %}




   <div class="content-header row align-items-center m-0">
                        <nav aria-label="breadcrumb" class="col-sm-4 order-sm-last mb-3 mb-sm-0 p-0 ">
                            <ol class="breadcrumb d-inline-flex font-weight-600 fs-13 bg-white mb-0 float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Transport Vehicle</a></li>
                                <li class="breadcrumb-item active">New Transport Vehicle</li>
                            </ol>
                        </nav>
                        <div class="col-sm-8 header-title p-0">
                            <div class="media">
                                <div class="header-icon text-success mr-3"><i class="typcn typcn-puzzle-outline"></i></div>
                                <div class="media-body">
                                    <h1 class="font-weight-bold">New Transport Vehicle</h1>
                                    <small>Some shit to say ...</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.Content Header (Page header)--> 
                    <div class="body-content">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card mb-12">
                                   
                                    <div class="card-body">
                                    

                                         <p>For custom Bootstrap form validation messages, you’ll need to add the <code>novalidate</code> boolean attribute
                                            to your <code>&lt;form&gt;</code>. This disables the browser default feedback tooltips, but still provides 
                                            access to the form validation APIs in JavaScript. Try to submit the form below; our JavaScript will intercept
                                            the submit button and relay feedback to you. When attempting to submit, you’ll see the <code>:invalid</code> and
                                            <code>:valid</code> styles applied to your form controls.</p>
                                        <p>Custom feedback styles apply custom colors, borders, focus styles, and background icons to better communicate
                                            feedback. Background icons for <code>&lt;select&gt;</code>s are only available with <code>.custom-select</code>, and not <code>.form-control</code>.</p>
                                        <form  method="post" action="{% url 'employee:add_vehicle' %}"   enctype="multipart/form-data"  >
                                             {% csrf_token %}  
                                            <div class="form-row">
                                                <div class="col-md-4 mb-3">
                                                    <label for="validationCustom01" class="font-weight-600">License Plate</label>
                                                    <input type="text" name="license_plate" class="form-control"  placeholder="U** ***" required>
                                                 
                                                </div>

                     


                                                <div class="col-md-4 mb-3">
                                                    <label for="validationCustom02" class="font-weight-600">Vehicle Contact Number</label>
                                                    
                                                    <input type="text" name="vehicle_contact" class="form-control"  placeholder="Enter contact number" required>
                                                   
                                                </div>
                                                <div class="col-md-4 mb-3">
                                                    <label for="validationCustomUsername" class="font-weight-600">Vehicle Color</label>
                                                    <div class="input-group">
                                                      
                                                        <input type="text" name="vehicle_color" class="form-control" placeholder="What color is the vehicle" required>
                                                       
                                                    </div>
                                                </div>
                                            </div>
                                          
                                         
                                            <button class="btn btn-success" type="submit">Add Vehicle</button>
                                        </form>



                                   
                                       
                                    </div>
                                </div>
                            </div>
                          
                        </div>

                        
                    </div><!--/.body content-->



{% endblock content %}